# Website settings
url: "https://jttoombs.github.io/"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Joseph Toombs"
description: "The home page of Yevgeniy (Jim) Brikman, co-founder of Gruntwork, author of &quot;Hello, Startup&quot; and &quot;Terraform: Up & Running&quot;, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "profile-photos/yevgeniy-brikman-medium.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/joseph-toombs/"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/profile.php?id=100017018141064"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/jttoombs"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jtoombs719@gmail.com"
    label: "Email"
    value: "jtoombs719@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: jttoombs/jttoombs.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
